# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.box_check_update = true

	config.vm.network "forwarded_port", guest: 80, host: 8210

   config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "Magento 2.1.0"
   end

  config.vm.provision :shell, path: "bootstrap.sh"

end
